import re

with open("src/components/AgriStore.tsx", "r") as f:
    content = f.read()

large_product_list = """const sampleProducts: Product[] = [
  {
    id: "prod-1",
    name: "Urea 46% Nitrogen",
    nameTe: "యూరియా 46% నత్రజని",
    category: "Fertilizer",
    price: 266,
    unit: "45 kg bag",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1628183204781-a9dc2db5a3d5?w=500&auto=format&fit=crop&q=60",
    description: "High quality urea fertilizer for enhanced crop growth.",
    descriptionTe: "పంటల పెరుగుదలకు నాణ్యమైన యూరియా ఎరువు.",
  },
  {
    id: "prod-2",
    name: "DAP (Di-ammonium Phosphate)",
    nameTe: "డీఏపీ ఎరువు (DAP)",
    category: "Fertilizer",
    price: 1350,
    unit: "50 kg bag",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1628183204781-a9dc2db5a3d5?w=500&auto=format&fit=crop&q=60",
    description: "Essential for root development and early plant growth.",
    descriptionTe: "వేరు అభివృద్ధికి మరియు మొక్కల ప్రారంభ పెరుగుదలకు అవసరమైన ఎరువు.",
  },
  {
    id: "prod-3",
    name: "Neem Oil Bio-Pesticide",
    nameTe: "వేప నూనె క్రిమిసంహారిణి",
    category: "Pesticide",
    price: 450,
    unit: "1 Liter",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1615486511484-92e172054dbb?w=500&auto=format&fit=crop&q=60",
    description: "Organic spray liquid for pest control.",
    descriptionTe: "పురుగుల నివారణకు ఆర్గానిక్ స్ప్రే లిక్విడ్.",
  },
  {
    id: "prod-4",
    name: "NPK 19:19:19 Water Soluble",
    nameTe: "ఎన్‌పికె 19:19:19 నీటిలో కరిగే ఎరువు",
    category: "Fertilizer",
    price: 180,
    unit: "1 kg",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1628183204781-a9dc2db5a3d5?w=500&auto=format&fit=crop&q=60",
    description: "Ideal for foliar spray and drip irrigation to improve yield.",
    descriptionTe: "దిగుబడిని పెంచడానికి ఫోలియర్ స్ప్రే మరియు డ్రిప్ ఇరిగేషన్‌కు అనువైనది.",
  },
  {
    id: "prod-5",
    name: "Chlorpyrifos 20% EC",
    nameTe: "క్లోర్‌పైరిఫాస్ 20% EC (పురుగుమందు)",
    category: "Pesticide",
    price: 320,
    unit: "500 ml",
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1584824486509-112e4181ff6b?w=500&auto=format&fit=crop&q=60",
    description: "Broad-spectrum insecticide for controlling various pests.",
    descriptionTe: "వివిధ మట్టి మరియు ఆకుల తెగుళ్ళను నివారించే క్రిమిసంహారిణి.",
  },
  {
    id: "prod-6",
    name: "BT Cotton Seeds (Bollgard II)",
    nameTe: "బిటి పత్తి విత్తనాలు (Bollgard II)",
    category: "Seeds",
    price: 850,
    unit: "450 gm",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1599813953796-03cead447f5b?w=500&auto=format&fit=crop&q=60",
    description: "High yielding cotton seeds with bollworm resistance.",
    descriptionTe: "అధిక దిగుబడినిచ్చే, పత్తి కాయతొలుచు పురుగును తట్టుకునే విత్తనాలు.",
  },
  {
    id: "prod-7",
    name: "Battery Operated Knapsack Sprayer",
    nameTe: "బ్యాటరీతో పనిచేసే స్ప్రేయర్ (16L)",
    category: "Equipment",
    price: 2400,
    unit: "1 Piece (16L)",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=500&auto=format&fit=crop&q=60",
    description: "16-Liter dual mode sprayer for efficient application.",
    descriptionTe: "సమర్థవంతంగా పిచికారీ చేయడానికి 16 లీటర్ల డ్యూయల్ మోడ్ స్ప్రేయర్.",
  },
  {
    id: "prod-8",
    name: "Paddy Seeds (BPT 5204)",
    nameTe: "వరి విత్తనాలు (BPT 5204 / సాంబ మసూరి)",
    category: "Seeds",
    price: 950,
    unit: "25 kg bag",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e8ac?w=500&auto=format&fit=crop&q=60",
    description: "Fine grain, high yielding paddy seed variety.",
    descriptionTe: "సన్న గింజలు, అధిక దిగుబడినిచ్చే వరి రకం.",
  },
  {
    id: "prod-9",
    name: "Zinc Sulphate 33%",
    nameTe: "జింక్ సల్ఫేట్ 33%",
    category: "Fertilizer",
    price: 450,
    unit: "5 kg bag",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1628183204781-a9dc2db5a3d5?w=500&auto=format&fit=crop&q=60",
    description: "Crucial for plant enzyme systems.",
    descriptionTe: "మొక్కల ఎంజైమ్ వ్యవస్థలకు కీలకం.",
  },
  {
    id: "prod-10",
    name: "Imidacloprid 17.8% SL",
    nameTe: "ఇమిడాక్లోప్రిడ్ 17.8% SL (పురుగుమందు)",
    category: "Pesticide",
    price: 380,
    unit: "250 ml",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1584824486509-112e4181ff6b?w=500&auto=format&fit=crop&q=60",
    description: "Effective systemic insecticide for sucking pests.",
    descriptionTe: "రసం పీల్చే పురుగుల నివారణకు సమర్థవంతమైన పురుగుమందు.",
  },
  {
    id: "prod-11",
    name: "Solar Insect Light Trap",
    nameTe: "సోలార్ ఇన్సెక్ట్ లైట్ ట్రాప్ (పురుగుల వల)",
    category: "Equipment",
    price: 1850,
    unit: "1 Piece",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1509391366360-12808b1a41f6?w=500&auto=format&fit=crop&q=60",
    description: "Eco-friendly pest management trap.",
    descriptionTe: "పర్యావరణ అనుకూల పురుగుల నివారణ వల.",
  },
  {
    id: "prod-12",
    name: "Tomato Seeds (Arka Rakshak)",
    nameTe: "టమాటా విత్తనాలు (అర్క రక్షక్)",
    category: "Seeds",
    price: 650,
    unit: "10 gm",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=500&auto=format&fit=crop&q=60",
    description: "High yielding hybrid tomato seeds.",
    descriptionTe: "అధిక దిగుబడినిచ్చే హైబ్రిడ్ టమాటా విత్తనాలు.",
  },
  {
    id: "prod-13",
    name: "Roundup Herbicide",
    nameTe: "రౌండప్ కలుపు నివారణ",
    category: "Pesticide",
    price: 450,
    unit: "1 Liter",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1593352216443-c045b84c8be2?w=500&auto=format&fit=crop&q=60",
    description: "Non-selective systemic herbicide.",
    descriptionTe: "కలుపు మొక్కలను నాశనం చేసే హెర్బిసైడ్.",
  },
  {
    id: "prod-14",
    name: "Coragen Insecticide",
    nameTe: "కోరాజెన్ పురుగుమందు",
    category: "Pesticide",
    price: 1850,
    unit: "150 ml",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1584824486509-112e4181ff6b?w=500&auto=format&fit=crop&q=60",
    description: "Advanced insecticide for long-lasting protection.",
    descriptionTe: "దీర్ఘకాలిక రక్షణ కోసం అత్యుత్తమ పురుగుమందు.",
  },
  {
    id: "prod-15",
    name: "MOP (Muriate of Potash)",
    nameTe: "పొటాష్ ఎరువు (MOP)",
    category: "Fertilizer",
    price: 1700,
    unit: "50 kg bag",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1628183204781-a9dc2db5a3d5?w=500&auto=format&fit=crop&q=60",
    description: "Improves crop quality and water retention.",
    descriptionTe: "పంట నాణ్యత, నీటి నిల్వ సామర్థ్యాన్ని పెంచుతుంది.",
  },
  {
    id: "prod-16",
    name: "Chilli Seeds (Tejaswini)",
    nameTe: "మిరప విత్తనాలు (తేజస్విని)",
    category: "Seeds",
    price: 450,
    unit: "10 gm",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1616421063628-98448a3e743a?w=500&auto=format&fit=crop&q=60",
    description: "High pungent hybrid chilli seeds.",
    descriptionTe: "అధిక కారం గల హైబ్రిడ్ విత్తనాలు.",
  },
  {
    id: "prod-17",
    name: "Heavy Duty Tarpaulin Sheet",
    nameTe: "టార్పాలిన్ కవర్ (24x30 ft)",
    category: "Equipment",
    price: 1250,
    unit: "24x30 ft",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?w=500&auto=format&fit=crop&q=60",
    description: "Waterproof tarpaulin for protecting crops.",
    descriptionTe: "పంటలను రక్షించడానికి వాటర్‌ప్రూఫ్ టార్పాలిన్.",
  },
  {
    id: "prod-18",
    name: "Drip Irrigation Kit",
    nameTe: "డ్రిప్ ఇరిగేషన్ కిట్ (1 ఎకరం)",
    category: "Equipment",
    price: 15000,
    unit: "1 Acre Kit",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1598466619623-289552d4b9b9?w=500&auto=format&fit=crop&q=60",
    description: "Complete drip irrigation kit for 1 acre.",
    descriptionTe: "1 ఎకరం పొలానికి పూర్తి డ్రిప్ ఇరిగేషన్ కిట్.",
  },
  {
    id: "prod-19",
    name: "Vermicompost Fertilizer",
    nameTe: "వానపాముల ఎరువు (వర్మీకంపోస్ట్)",
    category: "Fertilizer",
    price: 350,
    unit: "50 kg bag",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1628183204781-a9dc2db5a3d5?w=500&auto=format&fit=crop&q=60",
    description: "100% organic fertilizer rich in nutrients.",
    descriptionTe: "పోషకాలతో నిండిన 100% ఆర్గానిక్ ఎరువు.",
  },
  {
    id: "prod-20",
    name: "Onion Seeds (Nasik Red)",
    nameTe: "ఉల్లి విత్తనాలు (నాసిక్ రెడ్)",
    category: "Seeds",
    price: 1200,
    unit: "1 kg",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1623838421008-01334994ee31?w=500&auto=format&fit=crop&q=60",
    description: "High quality red onion seeds with good storage capacity.",
    descriptionTe: "మంచి నిల్వ సామర్థ్యం ఉన్న నాణ్యమైన ఉల్లి విత్తనాలు.",
  },
  {
    id: "prod-21",
    name: "Agricultural Sickle",
    nameTe: "కొడవలి (Sickle)",
    category: "Equipment",
    price: 150,
    unit: "1 Piece",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1603525281518-e7cdebb98dcd?w=500&auto=format&fit=crop&q=60",
    description: "Sharp and durable sickle for harvesting.",
    descriptionTe: "కోత కోసం పదునైన మరియు మన్నికైన కొడవలి.",
  },
  {
    id: "prod-22",
    name: "Mancozeb 75% WP Fungicide",
    nameTe: "మాంకోజెబ్ 75% WP (శిలీంద్ర సంహారిణి)",
    category: "Pesticide",
    price: 400,
    unit: "1 kg",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1584824486509-112e4181ff6b?w=500&auto=format&fit=crop&q=60",
    description: "Broad-spectrum contact fungicide.",
    descriptionTe: "విస్తృత శ్రేణి శిలీంద్ర సంహారిణి.",
  },
  {
    id: "prod-23",
    name: "PVC Delivery Pipe (2 inch)",
    nameTe: "PVC డెలివరీ పైపు (2 అంగుళాలు)",
    category: "Equipment",
    price: 850,
    unit: "30 Meters",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1598466619623-289552d4b9b9?w=500&auto=format&fit=crop&q=60",
    description: "Flexible and durable water delivery pipe.",
    descriptionTe: "నీటి సరఫరా కోసం మన్నికైన పైపు.",
  },
  {
    id: "prod-24",
    name: "Maize Seeds (Pioneer 3396)",
    nameTe: "మొక్కజొన్న విత్తనాలు (Pioneer 3396)",
    category: "Seeds",
    price: 1450,
    unit: "4 kg bag",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1601646271913-9069d2be0b48?w=500&auto=format&fit=crop&q=60",
    description: "High yielding hybrid maize seeds.",
    descriptionTe: "అధిక దిగుబడినిచ్చే మొక్కజొన్న హైబ్రిడ్ విత్తనాలు.",
  },
  {
    id: "prod-25",
    name: "Calcium Nitrate",
    nameTe: "కాల్షియం నైట్రేట్ ఎరువు",
    category: "Fertilizer",
    price: 1250,
    unit: "25 kg bag",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1628183204781-a9dc2db5a3d5?w=500&auto=format&fit=crop&q=60",
    description: "Water soluble fertilizer for cell wall strengthening.",
    descriptionTe: "కణకవచం బలోపేతం చేయడానికి నీటిలో కరిగే ఎరువు.",
  },
  {
    id: "prod-26",
    name: "Safety Gloves (Heavy Duty)",
    nameTe: "సేఫ్టీ గ్లోవ్స్",
    category: "Equipment",
    price: 250,
    unit: "1 Pair",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1591871261353-84f9715a3177?w=500&auto=format&fit=crop&q=60",
    description: "Protective gloves for handling chemicals and rough farming tasks.",
    descriptionTe: "రసాయనాలు మరియు కఠినమైన పనుల కోసం రక్షణ గ్లోవ్స్.",
  },
  {
    id: "prod-27",
    name: "Trichoderma Viride Bio-Fungicide",
    nameTe: "ట్రైకోడెర్మా విరిడే (బయో-ఫంగిసైడ్)",
    category: "Pesticide",
    price: 180,
    unit: "1 kg",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1584824486509-112e4181ff6b?w=500&auto=format&fit=crop&q=60",
    description: "Organic solution to prevent soil-borne diseases.",
    descriptionTe: "నేల ద్వారా వచ్చే తెగుళ్లను నివారించడానికి సేంద్రీయ ద్రావణం.",
  },
  {
    id: "prod-28",
    name: "Sunflower Seeds",
    nameTe: "పొద్దుతిరుగుడు విత్తనాలు",
    category: "Seeds",
    price: 950,
    unit: "2 kg bag",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1593026362840-7e40624a0d8e?w=500&auto=format&fit=crop&q=60",
    description: "High oil yielding sunflower hybrid seeds.",
    descriptionTe: "అధిక నూనె దిగుబడినిచ్చే పొద్దుతిరుగుడు విత్తనాలు.",
  },
  {
    id: "prod-29",
    name: "Weed Cutter / Brush Cutter",
    nameTe: "కలుపు కోసే యంత్రం (Brush Cutter)",
    category: "Equipment",
    price: 12500,
    unit: "1 Machine",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=500&auto=format&fit=crop&q=60",
    description: "Petrol operated brush cutter for clearing weeds and shrubs.",
    descriptionTe: "కలుపు మరియు పొదలను తొలగించడానికి పెట్రోల్ తో పనిచేసే యంత్రం.",
  },
  {
    id: "prod-30",
    name: "Seaweed Extract Liquid",
    nameTe: "సీవీడ్ ఎక్స్‌ట్రాక్ట్ లిక్విడ్",
    category: "Fertilizer",
    price: 550,
    unit: "1 Liter",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1628183204781-a9dc2db5a3d5?w=500&auto=format&fit=crop&q=60",
    description: "Natural plant growth promoter.",
    descriptionTe: "సహజమైన మొక్కల పెరుగుదల ప్రమోటర్.",
  },
  {
    id: "prod-31",
    name: "Spade (Phawda)",
    nameTe: "పార (Spade)",
    category: "Equipment",
    price: 350,
    unit: "1 Piece",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1603525281518-e7cdebb98dcd?w=500&auto=format&fit=crop&q=60",
    description: "Sturdy spade for digging and soil turning.",
    descriptionTe: "మట్టి త్రవ్వడానికి మరియు తిప్పడానికి గట్టి పార.",
  },
  {
    id: "prod-32",
    name: "Watermelon Seeds (Icebox)",
    nameTe: "పుచ్చకాయ విత్తనాలు (ఐస్బాక్స్)",
    category: "Seeds",
    price: 850,
    unit: "50 gm",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1587314168485-3236d6710814?w=500&auto=format&fit=crop&q=60",
    description: "Sweet, dark green outer rind watermelon seeds.",
    descriptionTe: "తీపి మరియు ముదురు ఆకుపచ్చ రంగు పుచ్చకాయ విత్తనాలు.",
  },
  {
    id: "prod-33",
    name: "Bavistin Systemic Fungicide",
    nameTe: "బావిస్టిన్ ఫంగిసైడ్",
    category: "Pesticide",
    price: 580,
    unit: "500 gm",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1584824486509-112e4181ff6b?w=500&auto=format&fit=crop&q=60",
    description: "Highly effective systemic fungicide.",
    descriptionTe: "అత్యంత ప్రభావవంతమైన సిస్టమిక్ ఫంగిసైడ్.",
  },
  {
    id: "prod-34",
    name: "Boron 20%",
    nameTe: "బోరాన్ 20% ఎరువు",
    category: "Fertilizer",
    price: 250,
    unit: "1 kg",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1628183204781-a9dc2db5a3d5?w=500&auto=format&fit=crop&q=60",
    description: "Essential micronutrient for flower and fruit development.",
    descriptionTe: "పువ్వులు మరియు పండ్ల అభివృద్ధికి అవసరమైన సూక్ష్మపోషకం.",
  },
  {
    id: "prod-35",
    name: "Water Pump (1.5 HP)",
    nameTe: "వాటర్ పంప్ (1.5 HP మోటార్)",
    category: "Equipment",
    price: 8500,
    unit: "1 Motor",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1598466619623-289552d4b9b9?w=500&auto=format&fit=crop&q=60",
    description: "Reliable centrifugal water pump for irrigation.",
    descriptionTe: "నీటి పారుదల కోసం నమ్మదగిన నీటి పంప్.",
  },
  {
    id: "prod-36",
    name: "Papaya Seeds (Red Lady)",
    nameTe: "బొప్పాయి విత్తనాలు (రెడ్ లేడీ)",
    category: "Seeds",
    price: 3200,
    unit: "10 gm",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1615486511484-92e172054dbb?w=500&auto=format&fit=crop&q=60",
    description: "World famous hybrid papaya seeds.",
    descriptionTe: "ప్రపంచ ప్రసిద్ధ హైబ్రిడ్ బొప్పాయి విత్తనాలు.",
  },
  {
    id: "prod-37",
    name: "Pseudomonas Fluorescens",
    nameTe: "సూడోమోనాస్ బయో-ఫంగిసైడ్",
    category: "Pesticide",
    price: 150,
    unit: "1 kg",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1584824486509-112e4181ff6b?w=500&auto=format&fit=crop&q=60",
    description: "Biological control agent against plant pathogens.",
    descriptionTe: "మొక్కల వ్యాధికారక క్రిములకు వ్యతిరేకంగా బయో-కంట్రోల్ ఏజెంట్.",
  },
  {
    id: "prod-38",
    name: "Secateurs (Pruning Shears)",
    nameTe: "కత్తిరింపు కత్తెర (Secateurs)",
    category: "Equipment",
    price: 450,
    unit: "1 Piece",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1603525281518-e7cdebb98dcd?w=500&auto=format&fit=crop&q=60",
    description: "Sharp pruning shears for cutting branches and stems.",
    descriptionTe: "కొమ్మలు మరియు కాడలను కత్తిరించడానికి కత్తెర.",
  },
  {
    id: "prod-39",
    name: "Magnesium Sulphate (Epsom Salt)",
    nameTe: "మెగ్నీషియం సల్ఫేట్ (ఎప్సమ్ సాల్ట్)",
    category: "Fertilizer",
    price: 200,
    unit: "5 kg",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1628183204781-a9dc2db5a3d5?w=500&auto=format&fit=crop&q=60",
    description: "Provides magnesium for chlorophyll production.",
    descriptionTe: "క్లోరోఫిల్ ఉత్పత్తికి మెగ్నీషియంను అందిస్తుంది.",
  },
  {
    id: "prod-40",
    name: "Gumboots (PVC)",
    nameTe: "గం బూట్స్ (నీటి బూట్లు)",
    category: "Equipment",
    price: 550,
    unit: "1 Pair",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1591871261353-84f9715a3177?w=500&auto=format&fit=crop&q=60",
    description: "Waterproof boots for farming in wet and muddy conditions.",
    descriptionTe: "తడి మరియు బురదలో వ్యవసాయం చేయడానికి వాటర్‌ప్రూఫ్ బూట్లు.",
  }
];"""

content = re.sub(r'const sampleProducts: Product\[\] = \[.*?\];', large_product_list, content, flags=re.DOTALL)

with open("src/components/AgriStore.tsx", "w") as f:
    f.write(content)

